services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8001:8000
    networks:
      - lan
    volumes:
      - /stacks/data/zoraxy/config/:/opt/zoraxy/config/
      - /stacks/data/zoraxy/plugin/:/opt/zoraxy/plugin/
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FASTGEOIP: "true"
      TZ: "Asia/Shanghai"
      
network:
  lan:
    external: true